### ISSUE TITLE
One question

### ISSUE THREAD

**Issue by BX-xb** [vihari/CSD#4]
Hi, when I run "python hw_train_and_test.py --dataset lipitk --num_train 50 
One error occurs:
FileNotFoundError: [Errno 2] No such file or directory: 'data/lipitk.pkl'
It seems the data for hand-written tasks is not automatically download
DATA_FLDR = "data/hpl-devnagari-iso-char-offline"
And I do not see the "data/hpl-devnagari-iso-char-offline" in the hw

**Comment by vihari** [comment]
Hi,  
Yes, that is not included in the repository. Download and extract it to the folder you mentioned.

**Comment by BX-xb** [comment]
where Can I download this file "hpl-devnagari-iso-char-offline"

**Comment by BX-xb** [comment]
Thank you!
when I run CG on nchd dataset, another error occurs:
FileNotFoundError: [Errno 2] No such file or directory: 'data/nhcd/nhcd/consonants/all_domains.txt'
where is the all_domains.txt?

**Comment by hugddygff** [comment]
> Thank you!
> when I run CG on nchd dataset, another error occurs:
> FileNotFoundError: [Errno 2] No such file or directory: 'data/nhcd/nhcd/consonants/all_domains.txt'
> where is the all_domains.txt?

Can you share the lipitk? since the dataset can not be downloaded now
