### ISSUE TITLE
One help

### ISSUE THREAD

**Issue by BX-xb** [vihari/CSD#5]
Hi!
When I run CG on nchd dataset, and I download the dataset and put them in the directory, one error occurs:
FileNotFoundError: [Errno 2] No such file or directory: 'data/nhcd/nhcd/consonants/all_domains.txt'
where is the all_domains.txt?

**Comment by vihari** [comment]
`all_domains.txt` really is just a listing of all user ids from `001` to `046`.  
You can just replace the file reading in this [line](https://github.com/vihari/CSD/blob/master/hw/nhcd.py#L73) with this line: `domain_ids = ["%03d" % _ for _ in range(1, 47)]`.
